In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Dataset Diabetes Type1 (Total).csv")
df

,Age,Sex,Area of Residence,HbA1c,Height,Weight,BMI,Duration of disease,Other diease,Adequate Nutrition,...,Standardized birth weight,Autoantibodies,Impaired glucose metabolism,Insulin taken,How Taken,Family History affected in Type 1 Diabetes,Family History affected in Type 2 Diabetes,Hypoglycemis,pancreatic disease affected in child,Affected
0,greater then 15,Female,Suburban,Over 7.5%,1.50,56.0,24.888889,4y,no,No,...,Middle quartiles,Yes,Yes,Yes,Injection,Yes,No,Yes,Yes,yes
1,greater then 15,Female,Suburban,Over 7.5%,1.48,58.0,26.479182,1w,none,No,...,Middle quartiles,Yes,No,Yes,Injection,Yes,Yes,Yes,Yes,yes
2,Less then 11,Female,Urban,Over 7.5%,1.20,46.0,31.944444,9d,none,Yes,...,Middle quartiles,Yes,No,Yes,Injection,Yes,No,No,No,yes
3,Less then 15,Female,Suburban,Over 7.5%,1.65,50.0,18.365473,1w,none,Yes,...,Middle quartiles,No,No,Yes,Injection,No,Yes,No,No,yes
4,Less then 15,Female,Suburban,Over 7.5%,1.61,59.0,22.761468,1m,liver problem,Yes,...,Middle quartiles,Yes,No,Yes,Injection,Yes,Yes,No,No,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,Less then 11,Male,Urban,Less then 7.5%,1.01,12.0,11.763553,none,none,Yes,...,Middle quartiles,Yes,No,No,No,No,Yes,No,No,No
302,Less then 11,Female,Suburban,Less then 7.5%,0.92,12.0,14.177694,none,none,Yes,...,Middle quartiles,Yes,No,No,No,No,Yes,No,No,No
303,Less then 5,Female,Suburban,Less then 7.5%,0.61,7.0,18.812147,none,none,Yes,...,Middle quartiles,Yes,No,No,No,No,No,No,No,No
304,Less then 11,Female,Suburban,Less then 7.5%,0.92,12.0,14.177694,none,none,Yes,...,Middle quartiles,Yes,No,No,No,No,Yes,No,No,No
305,Less then 5,Female,Urban,Less then 7.5%,0.61,5.0,13.437248,none,none,Yes,...,Middle quartiles,Yes,No,No,No,Yes,Yes,No,No,No